fix
Signed-off-by: Nikolay Mordvintsev <nikolay.mordvintsev@flant.com>

diff --git a/cve_scan/action.yml b/cve_scan/action.yml
--- a/cve_scan/action.yml
+++ b/cve_scan/action.yml
@@ -136,8 +136,8 @@ runs:
                 exit 1
               fi
             else
-                echo "ERROR: TAG TYPE is not defined!"
-                exit 1
+              echo "ERROR: TAG TYPE is not defined!"
+              exit 1
             fi
           fi
         fi
