fix
Signed-off-by: Nikolay Mordvintsev <nikolay.mordvintsev@flant.com>

diff --git a/cve_scan/action.yml b/cve_scan/action.yml
--- a/cve_scan/action.yml
+++ b/cve_scan/action.yml
@@ -134,6 +134,10 @@ runs:
               else
                 echo "ERROR: Provided tag \"${TAG}\" is not found in dev registry"
                 exit 1
+            else
+                echo "ERROR: TAG TYPE is not defined!"
+                exit 1
+            fi
           fi
         fi
         if [ "${SCAN_SEVERAL_LASTEST_RELEASES}" == "true" ]; then
